/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clave.h"

bool_t
xdr_CLAVE_get_value_result (XDR *xdrs, CLAVE_get_value_result *objp)
{
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->clave))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->valor1, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_val))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->V_valor2, 32,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
